### ISSUE TITLE
Problème technique (affichage)

### ISSUE THREAD

**Issue by Alouanelakkini** [lakkiniCom/IT-service#15]
Litige:
Etablissement: Ecole privée Draria
Administrateur: Chafik
Rapport : lorsque l'administrateur navigue dans l'information du compte (enseignant) ce dernier affiche le nom d'une autre école ( Double infinity ), nous prions l'équipe technique de régler ce problème le plus tôt possible

Cordialement!

**Comment by khaledesse** [comment]
Problème régler
