### ISSUE TITLE
vedeo of Draria school AD 

### ISSUE THREAD

**Issue by samkhaled** [lakkiniCom/IT-service#18]
Please make a fast solution for that ad vedeo we have put in the site , for more trust .
or just make a photo of the school with the contacts in its place .as it had taken a long time and didnt work 
thanks

**Comment by FrenkRio** [comment]
We have replaced the video with the info picture

**Comment by samkhaled** [comment]
Salam 
Thanks but it seems to be a visit card , maybe we choose another photo with details ,or can be designed . Will be much better 
Thanks

**Comment by FrenkRio** [comment]
Problem solved and the video has been uploaded successfully
