### ISSUE TITLE
Login & links 

### ISSUE THREAD

**Issue by Alouanelakkini** [lakkiniCom/IT-service#19]
pls make a fast solution for the following issues :

-parent & teacher  accounts are  not accessibe
-admin account ( once i login and i click on one off the dashboard services it will take me to the home page

**Comment by samkhaled** [comment]
please check and solve

**Comment by lakkiniCom** [comment]
- parent & teacher login resolved.

-I did not understand the second issue, can you give more details, please ?

**Comment by lakkiniCom** [comment]
Solved.
